//! The route table from `reference/config/routes.rb` (plus the framework routes `bin/rails routes`
//! lists: Active Storage, Turbo Native navigation, Action Mailbox, `/up`), and a router that
//! matches the way Rails' Journey does.
//!
//! Axum only sees one catch-all route; [`dispatch`] then picks the *first* route in table order
//! whose verb and pattern match, exactly as Rails does. That matters: `GET /rooms/opens` is
//! `rooms#show` with `id: "opens"` because `resources :rooms` is drawn before
//! `namespace :rooms`. Patterns use Rails syntax: `:param` matches `[^/.?]+`, `*glob` matches
//! lazily, and `(.:format)` is the optional format suffix (so `/rooms/1.json` sets
//! `params[:format]`). Path params are percent-decoded and merged over query and body params,
//! together with `controller` and `action`.
//!
//! ## Porting a controller
//!
//! Add `pub mod rooms;` (etc.) below, write `pub async fn show(c: &mut Ctx) -> Result` actions
//! that start with their before-action chain (see `crate::concerns`), and put `rooms::show` in
//! the matching rows. Declared routes whose action Rails
//! doesn't define (e.g. `first_runs#edit`) answer 404 like `AbstractController::ActionNotFound`:
//! map them to `action_not_found`. Never reorder, add or remove rows: the table must stay
//! identical to `bin/rails routes` (checked by the tests below against
//! `vectors/campfire_routes.json`, generated by `reference-tools/campfire/routes.rb`).

use std::sync::{Arc, LazyLock};

use campfire_kit::{Ctx, Error, Method, Param, ParamMap, Result, StatusCode};
use futures_util::future::BoxFuture;
use regex::{Regex, RegexSet};

use crate::active_storage;

// Controller modules (one per Rails controller namespace), plus the presenters that map rows to
// view models. Controller agents add their `pub mod` lines here.
pub mod accounts;
pub mod admin;
pub mod autocompletable;
pub mod first_runs;
pub mod messages;
pub mod presenters;
pub mod pwa;
pub mod qr_code;
pub mod rooms;
pub mod searches;
pub mod sessions;
pub mod unfurl_links;
pub mod users;
pub mod welcome;

/// Anything that can serve a route: every `async fn(&mut Ctx) -> Result` qualifies.
pub trait Action: Send + Sync + 'static {
    fn call<'a>(&'a self, c: &'a mut Ctx) -> BoxFuture<'a, Result>;
}

impl<F> Action for F
where
    F: for<'a> campfire_kit::ActionFn<'a>,
{
    fn call<'a>(&'a self, c: &'a mut Ctx) -> BoxFuture<'a, Result> {
        Box::pin(campfire_kit::ActionFn::call(self, c))
    }
}

pub struct Route {
    pub verb: Method,
    /// The Rails path spec, e.g. `/rooms/:room_id/messages(.:format)`. Compiled into `regex`; kept
    /// for the test that compares the table with `bin/rails routes`.
    #[cfg_attr(not(test), allow(dead_code))]
    pub pattern: &'static str,
    /// `controller#action`, as `bin/rails routes` prints it.
    pub endpoint: &'static str,
    pub defaults: &'static [(&'static str, &'static str)],
    action: Arc<dyn Action>,
    regex: Regex,
    names: Vec<String>,
}

impl Route {
    fn new(verb: Method, pattern: &'static str, endpoint: &'static str, action: impl Action) -> Self {
        let (regex, names) = compile(pattern);
        Self { verb, pattern, endpoint, defaults: &[], action: Arc::new(action), regex, names }
    }

    fn defaults(mut self, defaults: &'static [(&'static str, &'static str)]) -> Self {
        self.defaults = defaults;
        self
    }

    pub fn controller(&self) -> &'static str {
        self.endpoint.split_once('#').map_or(self.endpoint, |(controller, _)| controller)
    }

    pub fn action_name(&self) -> &'static str {
        self.endpoint.split_once('#').map_or("", |(_, action)| action)
    }
}

/// The route that matched the current request (`request.path_parameters` plus the endpoint),
/// available to actions as `c.current::<MatchedRoute>()`.
#[derive(Debug, Clone)]
pub struct MatchedRoute {
    pub endpoint: &'static str,
}

fn get(pattern: &'static str, endpoint: &'static str, action: impl Action) -> Route {
    Route::new(Method::GET, pattern, endpoint, action)
}

fn post(pattern: &'static str, endpoint: &'static str, action: impl Action) -> Route {
    Route::new(Method::POST, pattern, endpoint, action)
}

fn patch(pattern: &'static str, endpoint: &'static str, action: impl Action) -> Route {
    Route::new(Method::PATCH, pattern, endpoint, action)
}

fn put(pattern: &'static str, endpoint: &'static str, action: impl Action) -> Route {
    Route::new(Method::PUT, pattern, endpoint, action)
}

fn delete(pattern: &'static str, endpoint: &'static str, action: impl Action) -> Route {
    Route::new(Method::DELETE, pattern, endpoint, action)
}

/// `scope path: ":bot_key", defaults: { format: :json }`
const BOT_DEFAULTS: &[(&str, &str)] = &[("format", "json")];
/// `scope defaults: { user_id: "me" }`
const ME_DEFAULTS: &[(&str, &str)] = &[("user_id", "me")];

/// Every route, in `config/routes.rb` order.
pub fn routes() -> &'static [Route] {
    &ROUTES
}

// One row per route, like `bin/rails routes`, however long the row.
#[rustfmt::skip]
static ROUTES: LazyLock<Vec<Route>> = LazyLock::new(|| {
    vec![
        get("/", "welcome#show", welcome::show),
        get("/first_run/new(.:format)", "first_runs#new", action_not_found),
        get("/first_run/edit(.:format)", "first_runs#edit", action_not_found),
        get("/first_run(.:format)", "first_runs#show", first_runs::show),
        patch("/first_run(.:format)", "first_runs#update", action_not_found),
        put("/first_run(.:format)", "first_runs#update", action_not_found),
        delete("/first_run(.:format)", "first_runs#destroy", action_not_found),
        post("/first_run(.:format)", "first_runs#create", first_runs::create),
        get("/session/transfers/:id(.:format)", "sessions/transfers#show", sessions::transfers::show),
        patch("/session/transfers/:id(.:format)", "sessions/transfers#update", sessions::transfers::update),
        put("/session/transfers/:id(.:format)", "sessions/transfers#update", sessions::transfers::update),
        get("/session/new(.:format)", "sessions#new", sessions::new),
        get("/session/edit(.:format)", "sessions#edit", action_not_found),
        get("/session(.:format)", "sessions#show", action_not_found),
        patch("/session(.:format)", "sessions#update", action_not_found),
        put("/session(.:format)", "sessions#update", action_not_found),
        delete("/session(.:format)", "sessions#destroy", sessions::destroy),
        post("/session(.:format)", "sessions#create", sessions::create),
        get("/account/users(.:format)", "accounts/users#index", accounts::users::index),
        post("/account/users(.:format)", "accounts/users#create", action_not_found),
        get("/account/users/new(.:format)", "accounts/users#new", action_not_found),
        get("/account/users/:id/edit(.:format)", "accounts/users#edit", action_not_found),
        get("/account/users/:id(.:format)", "accounts/users#show", action_not_found),
        patch("/account/users/:id(.:format)", "accounts/users#update", accounts::users::update),
        put("/account/users/:id(.:format)", "accounts/users#update", accounts::users::update),
        delete("/account/users/:id(.:format)", "accounts/users#destroy", accounts::users::destroy),
        patch("/account/bots/:bot_id/key(.:format)", "accounts/bots/keys#update", accounts::bots::keys::update),
        put("/account/bots/:bot_id/key(.:format)", "accounts/bots/keys#update", accounts::bots::keys::update),
        get("/account/bots(.:format)", "accounts/bots#index", accounts::bots::index),
        post("/account/bots(.:format)", "accounts/bots#create", accounts::bots::create),
        get("/account/bots/new(.:format)", "accounts/bots#new", accounts::bots::new),
        get("/account/bots/:id/edit(.:format)", "accounts/bots#edit", accounts::bots::edit),
        get("/account/bots/:id(.:format)", "accounts/bots#show", action_not_found),
        patch("/account/bots/:id(.:format)", "accounts/bots#update", accounts::bots::update),
        put("/account/bots/:id(.:format)", "accounts/bots#update", accounts::bots::update),
        delete("/account/bots/:id(.:format)", "accounts/bots#destroy", accounts::bots::destroy),
        post("/account/join_code(.:format)", "accounts/join_codes#create", accounts::join_codes::create),
        get("/account/logo(.:format)", "accounts/logos#show", accounts::logos::show),
        delete("/account/logo(.:format)", "accounts/logos#destroy", accounts::logos::destroy),
        get("/account/custom_styles/edit(.:format)", "accounts/custom_styles#edit", accounts::custom_styles::edit),
        patch("/account/custom_styles(.:format)", "accounts/custom_styles#update", accounts::custom_styles::update),
        put("/account/custom_styles(.:format)", "accounts/custom_styles#update", accounts::custom_styles::update),
        get("/account/new(.:format)", "accounts#new", action_not_found),
        get("/account/edit(.:format)", "accounts#edit", accounts::edit),
        get("/account(.:format)", "accounts#show", action_not_found),
        patch("/account(.:format)", "accounts#update", accounts::update),
        put("/account(.:format)", "accounts#update", accounts::update),
        delete("/account(.:format)", "accounts#destroy", action_not_found),
        post("/account(.:format)", "accounts#create", action_not_found),
        get("/join/:join_code(.:format)", "users#new", users::new),
        post("/join/:join_code(.:format)", "users#create", users::create),
        get("/qr_code/:id(.:format)", "qr_code#show", qr_code::show),
        get("/users/:user_id/avatar(.:format)", "users/avatars#show", users::avatars::show),
        delete("/users/:user_id/avatar(.:format)", "users/avatars#destroy", users::avatars::destroy),
        delete("/users/:user_id/ban(.:format)", "users/bans#destroy", users::bans::destroy),
        post("/users/:user_id/ban(.:format)", "users/bans#create", users::bans::create),
        get("/users/:user_id/sidebar(.:format)", "users/sidebars#show", users::sidebars::show).defaults(ME_DEFAULTS),
        get("/users/:user_id/profile/new(.:format)", "users/profiles#new", action_not_found).defaults(ME_DEFAULTS),
        get("/users/:user_id/profile/edit(.:format)", "users/profiles#edit", action_not_found).defaults(ME_DEFAULTS),
        get("/users/:user_id/profile(.:format)", "users/profiles#show", users::profiles::show).defaults(ME_DEFAULTS),
        patch("/users/:user_id/profile(.:format)", "users/profiles#update", users::profiles::update).defaults(ME_DEFAULTS),
        put("/users/:user_id/profile(.:format)", "users/profiles#update", users::profiles::update).defaults(ME_DEFAULTS),
        delete("/users/:user_id/profile(.:format)", "users/profiles#destroy", action_not_found).defaults(ME_DEFAULTS),
        post("/users/:user_id/profile(.:format)", "users/profiles#create", action_not_found).defaults(ME_DEFAULTS),
        post("/users/:user_id/push_subscriptions/:push_subscription_id/test_notifications(.:format)", "users/push_subscriptions/test_notifications#create", users::push_subscriptions::test_notifications::create).defaults(ME_DEFAULTS),
        get("/users/:user_id/push_subscriptions(.:format)", "users/push_subscriptions#index", users::push_subscriptions::index).defaults(ME_DEFAULTS),
        post("/users/:user_id/push_subscriptions(.:format)", "users/push_subscriptions#create", users::push_subscriptions::create).defaults(ME_DEFAULTS),
        get("/users/:user_id/push_subscriptions/new(.:format)", "users/push_subscriptions#new", action_not_found).defaults(ME_DEFAULTS),
        get("/users/:user_id/push_subscriptions/:id/edit(.:format)", "users/push_subscriptions#edit", action_not_found).defaults(ME_DEFAULTS),
        get("/users/:user_id/push_subscriptions/:id(.:format)", "users/push_subscriptions#show", action_not_found).defaults(ME_DEFAULTS),
        patch("/users/:user_id/push_subscriptions/:id(.:format)", "users/push_subscriptions#update", action_not_found).defaults(ME_DEFAULTS),
        put("/users/:user_id/push_subscriptions/:id(.:format)", "users/push_subscriptions#update", action_not_found).defaults(ME_DEFAULTS),
        delete("/users/:user_id/push_subscriptions/:id(.:format)", "users/push_subscriptions#destroy", users::push_subscriptions::destroy).defaults(ME_DEFAULTS),
        get("/users/:id(.:format)", "users#show", users::show),
        get("/autocompletable/users(.:format)", "autocompletable/users#index", autocompletable::users::index),
        get("/rooms/:room_id/messages(.:format)", "messages#index", messages::index),
        post("/rooms/:room_id/messages(.:format)", "messages#create", messages::create),
        get("/rooms/:room_id/messages/new(.:format)", "messages#new", action_not_found),
        get("/rooms/:room_id/messages/:id/edit(.:format)", "messages#edit", messages::edit),
        get("/rooms/:room_id/messages/:id(.:format)", "messages#show", messages::show),
        patch("/rooms/:room_id/messages/:id(.:format)", "messages#update", messages::update),
        put("/rooms/:room_id/messages/:id(.:format)", "messages#update", messages::update),
        delete("/rooms/:room_id/messages/:id(.:format)", "messages#destroy", messages::destroy),
        post("/rooms/:room_id/:bot_key/messages/:message_id/boosts(.:format)", "messages/boosts/by_bots#create", messages::boosts::by_bots::create).defaults(BOT_DEFAULTS),
        delete("/rooms/:room_id/:bot_key/messages/:message_id/boosts/:id(.:format)", "messages/boosts/by_bots#destroy", messages::boosts::by_bots::destroy).defaults(BOT_DEFAULTS),
        get("/rooms/:room_id/:bot_key/messages(.:format)", "messages/by_bots#index", messages::by_bots::index).defaults(BOT_DEFAULTS),
        post("/rooms/:room_id/:bot_key/messages(.:format)", "messages/by_bots#create", messages::by_bots::create).defaults(BOT_DEFAULTS),
        patch("/rooms/:room_id/:bot_key/messages/:id(.:format)", "messages/by_bots#update", messages::by_bots::update).defaults(BOT_DEFAULTS),
        put("/rooms/:room_id/:bot_key/messages/:id(.:format)", "messages/by_bots#update", messages::by_bots::update).defaults(BOT_DEFAULTS),
        delete("/rooms/:room_id/:bot_key/messages/:id(.:format)", "messages/by_bots#destroy", messages::by_bots::destroy).defaults(BOT_DEFAULTS),
        get("/rooms/:room_id/refresh(.:format)", "rooms/refreshes#show", rooms::refreshes::show),
        get("/rooms/:room_id/settings(.:format)", "rooms/settings#show", missing_controller),
        get("/rooms/:room_id/involvement(.:format)", "rooms/involvements#show", rooms::involvements::show),
        patch("/rooms/:room_id/involvement(.:format)", "rooms/involvements#update", rooms::involvements::update),
        put("/rooms/:room_id/involvement(.:format)", "rooms/involvements#update", rooms::involvements::update),
        get("/rooms/:room_id/@:message_id(.:format)", "rooms#show", rooms::show),
        get("/rooms(.:format)", "rooms#index", rooms::index),
        post("/rooms(.:format)", "rooms#create", action_not_found),
        get("/rooms/new(.:format)", "rooms#new", action_not_found),
        get("/rooms/:id/edit(.:format)", "rooms#edit", action_not_found),
        get("/rooms/:id(.:format)", "rooms#show", rooms::show),
        patch("/rooms/:id(.:format)", "rooms#update", action_not_found),
        put("/rooms/:id(.:format)", "rooms#update", action_not_found),
        delete("/rooms/:id(.:format)", "rooms#destroy", rooms::destroy),
        get("/rooms/opens(.:format)", "rooms/opens#index", rooms::index),
        post("/rooms/opens(.:format)", "rooms/opens#create", rooms::opens::create),
        get("/rooms/opens/new(.:format)", "rooms/opens#new", rooms::opens::new),
        get("/rooms/opens/:id/edit(.:format)", "rooms/opens#edit", rooms::opens::edit),
        get("/rooms/opens/:id(.:format)", "rooms/opens#show", rooms::opens::show),
        patch("/rooms/opens/:id(.:format)", "rooms/opens#update", rooms::opens::update),
        put("/rooms/opens/:id(.:format)", "rooms/opens#update", rooms::opens::update),
        delete("/rooms/opens/:id(.:format)", "rooms/opens#destroy", rooms::destroy_without_room),
        get("/rooms/closeds(.:format)", "rooms/closeds#index", rooms::index),
        post("/rooms/closeds(.:format)", "rooms/closeds#create", rooms::closeds::create),
        get("/rooms/closeds/new(.:format)", "rooms/closeds#new", rooms::closeds::new),
        get("/rooms/closeds/:id/edit(.:format)", "rooms/closeds#edit", rooms::closeds::edit),
        get("/rooms/closeds/:id(.:format)", "rooms/closeds#show", rooms::closeds::show),
        patch("/rooms/closeds/:id(.:format)", "rooms/closeds#update", rooms::closeds::update),
        put("/rooms/closeds/:id(.:format)", "rooms/closeds#update", rooms::closeds::update),
        delete("/rooms/closeds/:id(.:format)", "rooms/closeds#destroy", rooms::destroy_without_room),
        get("/rooms/directs(.:format)", "rooms/directs#index", rooms::index),
        post("/rooms/directs(.:format)", "rooms/directs#create", rooms::directs::create),
        get("/rooms/directs/new(.:format)", "rooms/directs#new", rooms::directs::new),
        get("/rooms/directs/:id/edit(.:format)", "rooms/directs#edit", rooms::directs::edit),
        get("/rooms/directs/:id(.:format)", "rooms/directs#show", rooms::directs::show),
        patch("/rooms/directs/:id(.:format)", "rooms/directs#update", action_not_found),
        put("/rooms/directs/:id(.:format)", "rooms/directs#update", action_not_found),
        delete("/rooms/directs/:id(.:format)", "rooms/directs#destroy", rooms::directs::destroy),
        get("/messages/:message_id/boosts(.:format)", "messages/boosts#index", messages::boosts::index),
        post("/messages/:message_id/boosts(.:format)", "messages/boosts#create", messages::boosts::create),
        get("/messages/:message_id/boosts/new(.:format)", "messages/boosts#new", messages::boosts::new),
        get("/messages/:message_id/boosts/:id/edit(.:format)", "messages/boosts#edit", action_not_found),
        get("/messages/:message_id/boosts/:id(.:format)", "messages/boosts#show", action_not_found),
        patch("/messages/:message_id/boosts/:id(.:format)", "messages/boosts#update", action_not_found),
        put("/messages/:message_id/boosts/:id(.:format)", "messages/boosts#update", action_not_found),
        delete("/messages/:message_id/boosts/:id(.:format)", "messages/boosts#destroy", messages::boosts::destroy),
        get("/messages(.:format)", "messages#index", messages::index),
        post("/messages(.:format)", "messages#create", messages::create),
        get("/messages/new(.:format)", "messages#new", action_not_found),
        get("/messages/:id/edit(.:format)", "messages#edit", messages::edit),
        get("/messages/:id(.:format)", "messages#show", messages::show),
        patch("/messages/:id(.:format)", "messages#update", messages::update),
        put("/messages/:id(.:format)", "messages#update", messages::update),
        delete("/messages/:id(.:format)", "messages#destroy", messages::destroy),
        delete("/searches/clear(.:format)", "searches#clear", searches::clear),
        get("/searches(.:format)", "searches#index", searches::index),
        post("/searches(.:format)", "searches#create", searches::create),
        post("/unfurl_link(.:format)", "unfurl_links#create", unfurl_links::create),
        get("/webmanifest(.:format)", "pwa#manifest", pwa::manifest),
        get("/service-worker(.:format)", "pwa#service_worker", pwa::service_worker),
        get("/up(.:format)", "rails/health#show", health::show),
        get("/recede_historical_location(.:format)", "turbo/native/navigation#recede", turbo_native::recede),
        get("/resume_historical_location(.:format)", "turbo/native/navigation#resume", turbo_native::resume),
        get("/refresh_historical_location(.:format)", "turbo/native/navigation#refresh", turbo_native::refresh),
        post("/rails/action_mailbox/postmark/inbound_emails(.:format)", "action_mailbox/ingresses/postmark/inbound_emails#create", mailbox::ingress_not_configured),
        post("/rails/action_mailbox/relay/inbound_emails(.:format)", "action_mailbox/ingresses/relay/inbound_emails#create", mailbox::ingress_not_configured),
        post("/rails/action_mailbox/sendgrid/inbound_emails(.:format)", "action_mailbox/ingresses/sendgrid/inbound_emails#create", mailbox::ingress_not_configured),
        get("/rails/action_mailbox/mandrill/inbound_emails(.:format)", "action_mailbox/ingresses/mandrill/inbound_emails#health_check", mailbox::ingress_not_configured),
        post("/rails/action_mailbox/mandrill/inbound_emails(.:format)", "action_mailbox/ingresses/mandrill/inbound_emails#create", mailbox::ingress_not_configured),
        post("/rails/action_mailbox/mailgun/inbound_emails/mime(.:format)", "action_mailbox/ingresses/mailgun/inbound_emails#create", mailbox::ingress_not_configured),
        get("/rails/conductor/action_mailbox/inbound_emails(.:format)", "rails/conductor/action_mailbox/inbound_emails#index", mailbox::conductor),
        post("/rails/conductor/action_mailbox/inbound_emails(.:format)", "rails/conductor/action_mailbox/inbound_emails#create", mailbox::conductor),
        get("/rails/conductor/action_mailbox/inbound_emails/new(.:format)", "rails/conductor/action_mailbox/inbound_emails#new", mailbox::conductor),
        get("/rails/conductor/action_mailbox/inbound_emails/:id(.:format)", "rails/conductor/action_mailbox/inbound_emails#show", mailbox::conductor),
        get("/rails/conductor/action_mailbox/inbound_emails/sources/new(.:format)", "rails/conductor/action_mailbox/inbound_emails/sources#new", mailbox::conductor),
        post("/rails/conductor/action_mailbox/inbound_emails/sources(.:format)", "rails/conductor/action_mailbox/inbound_emails/sources#create", mailbox::conductor),
        post("/rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)", "rails/conductor/action_mailbox/reroutes#create", mailbox::conductor),
        post("/rails/conductor/action_mailbox/:inbound_email_id/incinerate(.:format)", "rails/conductor/action_mailbox/incinerates#create", mailbox::conductor),
        get("/rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)", "active_storage/blobs/redirect#show", active_storage::blobs_redirect),
        get("/rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)", "active_storage/blobs/proxy#show", active_storage::blobs_proxy),
        get("/rails/active_storage/blobs/:signed_id/*filename(.:format)", "active_storage/blobs/redirect#show", active_storage::blobs_redirect),
        get("/rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format)", "active_storage/representations/redirect#show", active_storage::representations_redirect),
        get("/rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)", "active_storage/representations/proxy#show", active_storage::representations_proxy),
        get("/rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)", "active_storage/representations/redirect#show", active_storage::representations_redirect),
        get("/rails/active_storage/disk/:encoded_key/*filename(.:format)", "active_storage/disk#show", active_storage::disk_show),
        put("/rails/active_storage/disk/:encoded_token(.:format)", "active_storage/disk#update", active_storage::disk_update),
        post("/rails/active_storage/direct_uploads(.:format)", "active_storage/direct_uploads#create", active_storage::direct_uploads_create),
        // --- Fork Extensions: User Management & Admin Settings ---
        get("/admin/users(.:format)", "admin/users#index", admin::index),
        post("/admin/users(.:format)", "admin/users#create", admin::create_user),
        post("/admin/settings/invites(.:format)", "admin/settings#invites", admin::toggle_invites),
        post("/admin/users/:id/role(.:format)", "admin/users#role", admin::update_role),
        post("/admin/users/:id/reset_password(.:format)", "admin/users#reset_password", admin::reset_password),
        post("/admin/users/:id/lock(.:format)", "admin/users#lock", admin::lock_user),
        post("/admin/users/:id/unlock(.:format)", "admin/users#unlock", admin::unlock_user),
        delete("/admin/users/:id(.:format)", "admin/users#destroy", admin::delete_user),
        // --- Fork Extension: Pinned Messages ---
        post("/rooms/:room_id/pin(.:format)", "rooms/pins#create", rooms::pins::create),
        delete("/rooms/:room_id/pin(.:format)", "rooms/pins#destroy", rooms::pins::destroy),
    ]
});

/// One verb's routes in table order, and a `RegexSet` of their patterns: recognition searches the
/// path once instead of trying each route's regex in turn (86 of them for GET).
struct VerbRoutes {
    verb: Method,
    routes: Vec<&'static Route>,
    patterns: RegexSet,
}

static ROUTES_BY_VERB: LazyLock<Vec<VerbRoutes>> = LazyLock::new(|| {
    let mut verbs: Vec<&Method> = Vec::new();
    for route in routes() {
        if !verbs.contains(&&route.verb) {
            verbs.push(&route.verb);
        }
    }
    verbs
        .into_iter()
        .map(|verb| {
            let routes: Vec<&'static Route> = routes().iter().filter(|route| route.verb == *verb).collect();
            let patterns = RegexSet::new(routes.iter().map(|route| route.regex.as_str())).expect("valid route patterns");
            VerbRoutes { verb: verb.clone(), routes, patterns }
        })
        .collect()
});

/// The single Axum entry point: find the route, install its path params, run its action.
pub async fn dispatch(c: &mut Ctx) -> Result {
    let path = normalize_path(c.request.path());
    let Some((route, path_params)) = recognize(&c.request.method, &path)? else {
        return Err(Error::NotFound);
    };
    install_path_params(c, path_params);
    c.set_current(MatchedRoute { endpoint: route.endpoint });
    route.action.call(c).await
}

/// The first route matching `method` and the normalized `path`, with its path parameters
/// (defaults, then captures, then `controller`/`action`). HEAD requests match GET routes.
pub fn recognize(method: &Method, path: &str) -> Result<Option<(&'static Route, ParamMap)>> {
    let verb = if *method == Method::HEAD { &Method::GET } else { method };
    let Some(candidates) = ROUTES_BY_VERB.iter().find(|candidates| candidates.verb == *verb) else { return Ok(None) };
    // The set's patterns are the verb's routes in table order, and it yields the ones that match
    // in ascending order, so the first is the first route in the table that matches.
    let Some(first) = candidates.patterns.matches(path).iter().next() else { return Ok(None) };
    let route = candidates.routes[first];
    let captures = route.regex.captures(path).expect("a route's regex matches wherever its pattern in the set does");
    Ok(Some((route, path_params(route, &captures)?)))
}

/// A matched route's path parameters: its defaults, then its captures (percent-decoded), then
/// `controller` and `action`.
fn path_params(route: &Route, captures: &regex::Captures) -> Result<ParamMap> {
    let mut params = ParamMap::new();
    for (name, value) in route.defaults {
        params.insert(*name, Param::Str(value.to_string()));
    }
    for (i, name) in route.names.iter().enumerate() {
        if let Some(value) = captures.get(i + 1) {
            params.insert(name.clone(), Param::Str(unescape_uri(value.as_str())?));
        }
    }
    params.insert("controller", Param::Str(route.controller().to_string()));
    params.insert("action", Param::Str(route.action_name().to_string()));
    Ok(params)
}

/// `params` is body params, then query params, then path params (`request.parameters`).
fn install_path_params(c: &mut Ctx, path_params: ParamMap) {
    let mut params = c.request_params.clone();
    params.merge(&c.query_params);
    params.merge(&path_params);
    c.params = params;
    c.path_params = path_params;
}

/// `Journey::Router::Utils.normalize_path`: one leading slash, repeated slashes squeezed,
/// trailing slashes dropped, percent-escapes upcased.
pub fn normalize_path(path: &str) -> String {
    let mut normalized = String::with_capacity(path.len() + 1);
    for c in format!("/{path}").chars() {
        if c == '/' && normalized.ends_with('/') {
            continue;
        }
        normalized.push(c);
    }
    while normalized.len() > 1 && normalized.ends_with('/') {
        normalized.pop();
    }
    static ESCAPE: LazyLock<Regex> = LazyLock::new(|| Regex::new("%[a-fA-F0-9]{2}").unwrap());
    ESCAPE.replace_all(&normalized, |m: &regex::Captures| m[0].to_uppercase()).into_owned()
}

/// `Journey::Router::Utils.unescape_uri`, then Rails' check that the parameter is valid UTF-8
/// (`ActionController::BadRequest` otherwise).
fn unescape_uri(value: &str) -> Result<String> {
    let bytes: Vec<u8> = percent_encoding::percent_decode_str(value).collect();
    String::from_utf8(bytes).map_err(|_| Error::BadRequest("Invalid path parameters: Invalid encoding".into()))
}

/// A Journey path spec as an anchored regex, plus its parameter names in order.
fn compile(pattern: &str) -> (Regex, Vec<String>) {
    let mut regex = String::from("^");
    let mut names = Vec::new();
    let mut chars = pattern.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '(' => regex.push_str("(?:"),
            ')' => regex.push_str(")?"),
            ':' | '*' => {
                let mut name = String::new();
                while let Some(&n) = chars.peek().filter(|n| n.is_ascii_alphanumeric() || **n == '_') {
                    name.push(n);
                    chars.next();
                }
                regex.push_str(if c == ':' { "([^/.?]+)" } else { "(.+?)" });
                names.push(name);
            }
            other => regex.push_str(&regex::escape(&other.to_string())),
        }
    }
    regex.push('$');
    (Regex::new(&regex).expect("valid route pattern"), names)
}

/// A declared route whose action the controller doesn't define (`AbstractController::ActionNotFound`).
pub async fn action_not_found(_c: &mut Ctx) -> Result {
    Err(Error::NotFound)
}

/// A declared route whose controller doesn't exist, e.g. `resource :settings` under rooms: the
/// reference answers 500 (the controller constant fails to load).
pub async fn missing_controller(c: &mut Ctx) -> Result {
    let endpoint = c.current::<MatchedRoute>().map_or("?", |route| route.endpoint);
    Err(Error::internal(anyhow::anyhow!("uninitialized constant for {endpoint}")))
}

/// `Rails::HealthController`
mod health {
    use campfire_kit::format;

    use super::*;

    pub async fn show(c: &mut Ctx) -> Result {
        match c.respond_to(&[&format::HTML, &format::JSON])? {
            f if *f == format::JSON => {
                let timestamp = jiff::Timestamp::from_second(c.now().as_second()).unwrap_or(c.now());
                c.json(StatusCode::OK, &serde_json::json!({ "status": "up", "timestamp": timestamp.to_string() }))
            }
            _ => Ok(c.html(r#"<!DOCTYPE html><html><body style="background-color: green"></body></html>"#)),
        }
    }
}

/// `Turbo::Native::NavigationController` (turbo-rails)
mod turbo_native {
    use super::*;

    pub async fn recede(c: &mut Ctx) -> Result {
        Ok(c.html("Going back…"))
    }

    pub async fn resume(c: &mut Ctx) -> Result {
        Ok(c.html("Staying put…"))
    }

    pub async fn refresh(c: &mut Ctx) -> Result {
        Ok(c.html("Refreshing…"))
    }
}

/// Action Mailbox's ingress and conductor routes, which Campfire doesn't use.
mod mailbox {
    use super::*;

    /// `ActionMailbox::BaseController#ensure_configured`: no ingress is configured.
    pub async fn ingress_not_configured(c: &mut Ctx) -> Result {
        Ok(c.head(StatusCode::NOT_FOUND))
    }

    /// `Rails::Conductor::BaseController`: CSRF first, then `ensure_development_env`.
    pub async fn conductor(c: &mut Ctx) -> Result {
        c.verify_authenticity_token()?;
        Ok(c.head(StatusCode::FORBIDDEN))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(serde::Deserialize)]
    struct Vectors {
        routes: Vec<RailsRoute>,
        recognitions: Vec<Recognition>,
    }

    #[derive(serde::Deserialize)]
    struct RailsRoute {
        verb: String,
        path: String,
        endpoint: String,
        defaults: std::collections::BTreeMap<String, String>,
    }

    #[derive(serde::Deserialize)]
    struct Recognition {
        verb: String,
        path: String,
        endpoint: Option<String>,
        params: std::collections::BTreeMap<String, String>,
    }

    fn vectors() -> Vectors {
        let json = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../vectors/campfire_routes.json"));
        serde_json::from_str(json).unwrap()
    }

    /// Controllers the reference routes to but doesn't define (recognize_path raises for them).
    const MISSING_CONTROLLERS: &[&str] = &["rooms/settings"];

    #[test]
    fn the_table_is_rails_routes_in_order() {
        let rails = vectors().routes;
        let ours = routes();
        let ours_rails = &ours[..rails.len()];
        for (i, (rails, ours)) in rails.iter().zip(ours_rails).enumerate() {
            let defaults: std::collections::BTreeMap<String, String> =
                ours.defaults.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect();
            assert_eq!(
                (rails.verb.as_str(), rails.path.as_str(), rails.endpoint.as_str(), &rails.defaults),
                (ours.verb.as_str(), ours.pattern, ours.endpoint, &defaults),
                "route #{i}"
            );
        }
        let fork_routes = ours[rails.len()..].iter().all(|r| r.endpoint.starts_with("admin/") || r.endpoint.starts_with("rooms/pins#"));
        assert!(fork_routes, "every extra route after Rails table must be a fork extension");
    }

    #[test]
    fn recognizes_paths_like_rails() {
        for sample in vectors().recognitions {
            let method = Method::from_bytes(sample.verb.as_bytes()).unwrap();
            let path = normalize_path(&sample.path);
            let recognized = recognize(&method, &path).unwrap();
            match (&sample.endpoint, recognized) {
                (Some(endpoint), Some((route, params))) => {
                    assert_eq!(route.endpoint, endpoint, "{} {}", sample.verb, sample.path);
                    let mut params: std::collections::BTreeMap<String, String> =
                        params.iter().map(|(k, v)| (k.clone(), v.as_str().unwrap().to_string())).collect();
                    params.remove("controller");
                    params.remove("action");
                    assert_eq!(params, sample.params, "{} {}", sample.verb, sample.path);
                }
                (None, Some((route, _))) => {
                    assert!(MISSING_CONTROLLERS.contains(&route.controller()), "{} {} matched {}", sample.verb, sample.path, route.endpoint)
                }
                (None, None) => {}
                (Some(endpoint), None) => panic!("{} {} should be {endpoint}", sample.verb, sample.path),
            }
        }
    }

    /// Recognition the straightforward way: try the verb's routes in table order and take the
    /// first whose regex matches. `recognize` must agree with it on every path.
    fn recognize_by_scanning(method: &Method, path: &str) -> Result<Option<(&'static Route, ParamMap)>> {
        let verb = if *method == Method::HEAD { &Method::GET } else { method };
        for route in routes().iter().filter(|route| route.verb == *verb) {
            if let Some(captures) = route.regex.captures(path) {
                return Ok(Some((route, path_params(route, &captures)?)));
            }
        }
        Ok(None)
    }

    /// The matched row's index and params, or the error, in a form that compares.
    type Outcome = std::result::Result<Option<(usize, ParamMap)>, String>;

    fn outcome(recognized: Result<Option<(&'static Route, ParamMap)>>) -> Outcome {
        match recognized {
            Ok(Some((route, params))) => Ok(Some((routes().iter().position(|row| std::ptr::eq(row, route)).unwrap(), params))),
            Ok(None) => Ok(None),
            Err(error) => Err(format!("{error:?}")),
        }
    }

    /// A route pattern's paths: with and without the format, and with its params filled in with
    /// ids, words, percent-escapes and raw UTF-8 (which the server passes through unescaped, and
    /// which the patterns' Unicode classes match as multi-byte sequences).
    fn filled_in(pattern: &str) -> Vec<String> {
        static PARAM: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"([:*])(\w+)").unwrap());
        let mut paths = Vec::new();
        for format in ["", ".:format"] {
            let pattern = pattern.replace("(.:format)", format);
            for (param, glob) in [("1", "photo"), ("opens", "dir/photo.tar.gz"), ("caf%C3%A9", "a%2Fb/c%20d"), ("café", "😀/dir/é.tar")]
            {
                paths.push(
                    PARAM
                        .replace_all(&pattern, |c: &regex::Captures| match (&c[1], &c[2]) {
                            (":", "format") => "json",
                            (":", _) => param,
                            _ => glob,
                        })
                        .into_owned(),
                );
            }
        }
        paths
    }

    /// `path` and its near misses: other formats, trailing and doubled slashes, a character or a
    /// segment more or less, other case, a query, escapes that aren't UTF-8, and raw UTF-8.
    fn variants(path: &str) -> Vec<String> {
        let mut variants =
            vec![path.to_string(), path.to_uppercase(), path.replacen('/', "//", 2), path.trim_start_matches('/').to_string()];
        for suffix in [".json", ".turbo_stream", ".1.2", ".", "/", "//", "x", "/x", "/new", "/edit", "?q=1", "%FF", "%2F", "é", "😀.json"]
        {
            variants.push(format!("{path}{suffix}"));
        }
        if let Some((last, _)) = path.char_indices().last() {
            variants.push(path[..last].to_string());
        }
        if let Some((parent, _)) = path.rsplit_once('/') {
            variants.extend([parent.to_string(), format!("{parent}/%E9"), format!("{parent}/@42"), format!("{parent}/opens")]);
        }
        variants
    }

    /// Every path the Rails vectors recognize and every route pattern filled in, as given and
    /// normalized, with their near misses.
    fn corpus() -> std::collections::BTreeSet<String> {
        let vectors = vectors();
        let seeds = vectors
            .recognitions
            .iter()
            .map(|sample| sample.path.clone())
            .chain(vectors.routes.iter().flat_map(|route| filled_in(&route.path)));
        seeds.flat_map(|seed| [normalize_path(&seed), seed]).flat_map(|path| variants(&path)).collect()
    }

    #[test]
    fn recognizes_like_a_first_match_scan() {
        let corpus = corpus();
        let verbs = [Method::GET, Method::HEAD, Method::POST, Method::PATCH, Method::PUT, Method::DELETE, Method::OPTIONS];
        let (mut rows, mut missed, mut failed) = (std::collections::BTreeSet::new(), 0, 0);
        for verb in &verbs {
            for path in &corpus {
                let expected = outcome(recognize_by_scanning(verb, path));
                assert_eq!(outcome(recognize(verb, path)), expected, "{verb} {path}");
                match expected {
                    Ok(Some((row, _))) => {
                        rows.insert(row);
                    }
                    Ok(None) => missed += 1,
                    Err(_) => failed += 1,
                }
            }
        }
        // Every row answers some path, except the three that `GET /rooms/:id`, drawn first, shadows.
        let unmatched: Vec<String> = routes()
            .iter()
            .enumerate()
            .filter(|(i, _)| !rows.contains(i))
            .map(|(_, route)| format!("{} {}", route.verb, route.pattern))
            .collect();
        assert_eq!(unmatched, ["GET /rooms/opens(.:format)", "GET /rooms/closeds(.:format)", "GET /rooms/directs(.:format)"]);
        assert!(missed > 10_000 && failed > 1_000, "{missed} paths missed, {failed} failed");
    }

    /// Times `recognize` on the paths the page benchmarks request, `/up`, Active Storage URLs and a
    /// 404 (bench/results/routing-20260930):
    /// `cargo test --release -p campfire --bin campfire -- --ignored --nocapture times_recognition`
    #[test]
    #[ignore = "a timing harness; run it in a release build"]
    fn times_recognition() {
        let long_filename = format!("/rails/active_storage/blobs/redirect/abc--def/{}photo.png", "dir/café.tar/".repeat(160));
        let paths: &[(&str, &str)] = &[
            ("room_show", "/rooms/12"),
            ("messages_page", "/rooms/12/messages"),
            ("search", "/searches"),
            ("up", "/up"),
            (
                "representation",
                "/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NDIsInB1ciI6ImJsb2JfaWQifX0=--4c2a1f0e9b8d7c6a5f4e3d2c1b0a9f8e7d6c5b4a/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwicmVzaXplX3RvX2xpbWl0IjpbMTIwMCwxMjAwXX0sInB1ciI6InZhcmlhdGlvbiJ9fQ==--0f1e2d3c4b5a69788796a5b4c3d2e1f0a1b2c3d4/photo.png",
            ),
            ("long filename", &long_filename),
            ("404", "/wp-login.php"),
        ];
        const SAMPLES: usize = 9;
        const ITERATIONS: u32 = 200_000;

        // The first thread to use a regex owns its fast cache slot; the server's other workers
        // take the shared pool. Warm up on a thread of its own so the timed thread is one of those.
        std::thread::scope(|scope| scope.spawn(|| paths.iter().for_each(|(_, path)| drop(recognize(&Method::GET, path)))).join().unwrap());
        for (name, path) in paths {
            let mut samples: Vec<f64> = (0..SAMPLES)
                .map(|_| {
                    let started = std::time::Instant::now();
                    for _ in 0..ITERATIONS {
                        std::hint::black_box(recognize(&Method::GET, std::hint::black_box(path)).unwrap());
                    }
                    started.elapsed().as_nanos() as f64 / f64::from(ITERATIONS)
                })
                .collect();
            samples.sort_by(f64::total_cmp);
            eprintln!("{name:<15} median {:>6.0} ns  (min {:.0}, max {:.0})", samples[SAMPLES / 2], samples[0], samples[SAMPLES - 1]);
        }
    }

    #[test]
    fn normalizes_paths() {
        assert_eq!(normalize_path(""), "/");
        assert_eq!(normalize_path("//rooms//1//"), "/rooms/1");
        assert_eq!(normalize_path("/a%2fb"), "/a%2Fb");
    }
}
