services:
  test_campfire:
    image: dogming/once-campfire-rust:latest
    container_name: test_campfire
    restart: unless-stopped
    ports:
      - "3002:80"
    volumes:
      - test_campfire_storage:/rails/storage
    env_file:
      - .env
    environment:
      - DISABLE_SSL=true

volumes:
  test_campfire_storage:
    name: test-campfire_test_campfire_storage
